### ISSUE TITLE
Missing day 11

### ISSUE THREAD

**Issue by josefandersson** [Dunklas/aoc-2022#1]
Hello I need solution for 11b, pls fix 😢

**Comment by Dunklas** [comment]
Sorry Josef! Fixed now!!

**Comment by josefandersson** [comment]
TACK
Och åååå vad frustrerande, jag tänkte på det (rest på produkten av allas test) när jag var ute och gick senare på kvällen men testade det aldrig för kändes som att det skulle bli för högt vet inte varför 🤤
